#Exclude number of words to be lint
disabled_rules: # rule identifiers turned on by default to exclude from running
 - line_length
#Exclude third party library to be lint

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
