version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.4
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - checkout
  
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: Noted

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output


workflows:
  build-test-lint:
    jobs:

      - build-and-test
